(function(){
  const root=document.documentElement;
  const state={category:'all',query:''};
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc=(v)=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function resolveTheme(){const t=localStorage.getItem('theme')||'system'; root.classList.toggle('dark',t==='dark'||(t==='system'&&matchMedia('(prefers-color-scheme: dark)').matches)); root.classList.toggle('light',t==='light'||(t==='system'&&!matchMedia('(prefers-color-scheme: dark)').matches));}
  function setTheme(t){localStorage.setItem('theme',t);resolveTheme(); updateThemeButtons();}
  function updateThemeButtons(){const t=localStorage.getItem('theme')||'system'; $$('#theme-menu button').forEach(b=>b.dataset.active=b.dataset.theme===t?'true':'false');}
  function gameCard(g){return `<article class="game-card group min-w-0 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg dark:border-white/10 dark:bg-white/[0.045]" data-category="${esc(g.category)}" data-tags="${esc(g.tags.join(' '))}" data-search="${esc((g.title+' '+g.category+' '+g.tags.join(' ')).toLowerCase())}"><a class="block" href="pages/games/${esc(g.slug)}.html" aria-label="View ${esc(g.title)} details"><div class="relative aspect-[4/3] overflow-hidden bg-slate-900"><img src="${esc(g.image)}" alt="${esc(g.title)} artwork" loading="lazy" class="h-full w-full object-cover transition duration-500 group-hover:scale-105"><span class="absolute left-2 top-2 rounded-full bg-slate-950/70 px-2 py-1 text-[10px] font-bold text-white backdrop-blur">#${g.rank}</span></div><div class="p-2.5 sm:p-3"><h3 class="truncate text-sm font-bold text-slate-900 dark:text-white">${esc(g.title)}</h3><div class="mt-1 flex items-center justify-between gap-1 text-[10px] text-slate-500 dark:text-slate-400"><span>★ ${esc(g.rating)}</span><span>${esc(g.bonus)}</span></div><div class="mt-2 flex items-center justify-between gap-1"><span class="truncate text-[10px] text-slate-500 dark:text-slate-400">Withdraw ${esc(g.withdraw)}</span><span class="rounded-lg bg-blue-500 px-2 py-1 text-[10px] font-bold text-white">PLAY</span></div></div></a></article>`;}
  function renderFeatured(){const host=$('#featured-grid');if(!host)return;host.innerHTML=window.GAMES.filter(g=>g.featured).slice(0,3).map(g=>`<article class="group relative overflow-hidden rounded-3xl border border-white/10 bg-slate-900 shadow-2xl"><a href="pages/games/${esc(g.slug)}.html" class="block"><div class="aspect-[16/10] overflow-hidden"><img src="${esc(g.image)}" alt="${esc(g.title)} featured artwork" class="h-full w-full object-cover transition duration-500 group-hover:scale-105"></div><div class="absolute inset-x-0 bottom-0 bg-gradient-to-t from-slate-950 via-slate-950/80 to-transparent p-4 pt-16"><div class="flex items-end justify-between gap-3"><div><div class="mb-1 flex gap-2 text-xs"><span class="pill bg-white/10 text-white">★ ${esc(g.rating)}</span><span class="pill bg-blue-500/20 text-blue-200">Bonus ${esc(g.bonus)}</span></div><h3 class="text-lg font-extrabold text-white">${esc(g.title)}</h3><p class="mt-1 text-xs text-slate-300">Withdraw ${esc(g.withdraw)}</p></div><span class="btn-primary shrink-0">Visit</span></div></div></a></article>`).join('');}
  function filter(){const cards=$$('.game-card');let visible=0;cards.forEach(c=>{const q=state.query.toLowerCase().trim();const matchQ=!q||c.dataset.search.includes(q);const matchC=state.category==='all'||c.dataset.category===state.category||c.dataset.tags.split(' ').includes(state.category);const show=matchQ&&matchC;c.classList.toggle('hidden',!show);if(show)visible++;});const empty=$('#empty-state');if(empty)empty.classList.toggle('hidden',visible!==0);const count=$('#results-count');if(count)count.textContent=`${visible} ${visible===1?'game':'games'}`;}
  function renderGames(){const host=$('#games-grid');if(!host)return;host.innerHTML=window.GAMES.map(gameCard).join('');filter();}
  function initSearch(){const input=$('#search');const clear=$('#clear-search');if(!input)return;input.addEventListener('input',()=>{state.query=input.value;filter();clear.classList.toggle('hidden',!input.value)});clear.addEventListener('click',()=>{input.value='';state.query='';clear.classList.add('hidden');input.focus();filter();});}
  function initTabs(){$$('.category-tab').forEach(b=>b.addEventListener('click',()=>{$$('.category-tab').forEach(x=>x.classList.remove('bg-blue-500','text-white'));b.classList.add('bg-blue-500','text-white');state.category=b.dataset.category;filter();}));}
  function initMenu(){const btn=$('#menu-btn'),menu=$('#mobile-menu');if(!btn)return;btn.addEventListener('click',()=>{const open=!menu.classList.contains('hidden');menu.classList.toggle('hidden',open);btn.setAttribute('aria-expanded',String(!open));});}
  function initTheme(){const toggle=$('#theme-toggle');const menu=$('#theme-menu');if(toggle){toggle.addEventListener('click',()=>menu.classList.toggle('hidden'));document.addEventListener('click',e=>{if(!menu.contains(e.target)&&e.target!==toggle)menu.classList.add('hidden');});$$('#theme-menu button').forEach(b=>b.addEventListener('click',()=>{setTheme(b.dataset.theme);menu.classList.add('hidden');}));} resolveTheme();matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if((localStorage.getItem('theme')||'system')==='system')resolveTheme();});updateThemeButtons();}
  function initPromo(){const modal=$('#promo-modal');if(!modal)return;const key='promoClosedAt';const closed=Number(localStorage.getItem(key)||0);if(Date.now()-closed<86400000)return;setTimeout(()=>modal.classList.remove('hidden'),3000);$('#promo-close').addEventListener('click',()=>{modal.classList.add('hidden');localStorage.setItem(key,String(Date.now()));});modal.addEventListener('click',e=>{if(e.target===modal){modal.classList.add('hidden');localStorage.setItem(key,String(Date.now()));}});document.addEventListener('keydown',e=>{if(e.key==='Escape')modal.classList.add('hidden');});}
  function initShare(){const btn=$('#share-btn'),menu=$('#share-menu');if(!btn)return;const url=location.href,title=document.title;text=`🎮 Check out ${title} — ${url}`;btn.addEventListener('click',async()=>{if(navigator.share){try{await navigator.share({title,text,url});return;}catch(e){}}menu.classList.toggle('hidden');});const wa=$('#share-wa'),tg=$('#share-tg'),fb=$('#share-fb'),x=$('#share-x'),copy=$('#share-copy');if(wa)wa.href=`https://api.whatsapp.com/send?text=${encodeURIComponent(text)}`;if(tg)tg.href=`https://t.me/share/url?url=${encodeURIComponent(url)}&text=${encodeURIComponent(title)}`;if(fb)fb.href=`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`;if(x)x.href=`https://twitter.com/intent/tweet?url=${encodeURIComponent(url)}&text=${encodeURIComponent(title)}`;if(copy)copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(url);copy.textContent='Copied!';setTimeout(()=>copy.textContent='Copy Link',1600);}catch(e){copy.textContent='Copy failed';}});}
  document.addEventListener('DOMContentLoaded',()=>{renderFeatured();renderGames();initSearch();initTabs();initMenu();initTheme();initPromo();initShare();});
})();
