window.GAMES = [
  {id:'game-001',rank:1,title:'Yono Slots',slug:'yono-slots',image:'assets/images/game-1.svg',category:'slots',bonus:'₹500',rating:'4.8',withdraw:'₹10',featured:true,tags:['slots','popular','new'],description:'A directory listing for Yono Slots. Verify current bonus, eligibility, rules and availability on the linked destination before participating.',features:['Game listing information','Category and tag discovery','Direct external destination'],playUrl:'https://example.com/'},
  {id:'game-002',rank:2,title:'Yono Rummy',slug:'yono-rummy',image:'assets/images/game-2.svg',category:'rummy',bonus:'₹500',rating:'4.7',withdraw:'₹10',featured:true,tags:['rummy','popular'],description:'A directory listing for Yono Rummy. Any bonus or withdrawal information shown here should be confirmed on the destination website.',features:['Rummy category listing','Search and filtering','Shareable detail page'],playUrl:'https://example.com/'},
  {id:'game-003',rank:3,title:'Teen Patti Master',slug:'teen-patti-master',image:'assets/images/game-3.svg',category:'teen-patti',bonus:'₹300',rating:'4.6',withdraw:'₹10',featured:true,tags:['teen-patti','popular'],description:'A directory listing for Teen Patti Master. This site provides informational links and does not host the game.',features:['Teen Patti listing','Related games','SEO-ready detail page'],playUrl:'https://example.com/'},
  {id:'game-004',rank:4,title:'Yono 777',slug:'yono-777',image:'assets/images/game-4.svg',category:'slots',bonus:'₹300',rating:'4.5',withdraw:'₹10',featured:false,tags:['slots','new'],description:'A sample static directory entry for Yono 777.',features:['Static listing','External destination','Share support'],playUrl:'https://example.com/'},
  {id:'game-005',rank:5,title:'Teen Patti Gold',slug:'teen-patti-gold',image:'assets/images/game-5.svg',category:'teen-patti',bonus:'₹250',rating:'4.5',withdraw:'₹10',featured:false,tags:['teen-patti','popular'],description:'A sample static directory entry for Teen Patti Gold.',features:['Mobile-first listing','Related content','Client-side filtering'],playUrl:'https://example.com/'},
  {id:'game-006',rank:6,title:'Jaiho 777',slug:'jaiho-777',image:'assets/images/game-6.svg',category:'slots',bonus:'₹400',rating:'4.4',withdraw:'₹10',featured:false,tags:['slots'],description:'A sample static directory entry for Jaiho 777.',features:['Category filter','Share system','Static SEO page'],playUrl:'https://example.com/'},
  {id:'game-007',rank:7,title:'Classic Rummy',slug:'classic-rummy',image:'assets/images/game-7.svg',category:'rummy',bonus:'₹200',rating:'4.3',withdraw:'₹10',featured:false,tags:['rummy','new'],description:'A sample static directory entry for Classic Rummy.',features:['Responsive cards','Search support','External CTA'],playUrl:'https://example.com/'},
  {id:'game-008',rank:8,title:'Lucky Slots',slug:'lucky-slots',image:'assets/images/game-8.svg',category:'slots',bonus:'₹250',rating:'4.2',withdraw:'₹10',featured:false,tags:['slots','popular'],description:'A sample static directory entry for Lucky Slots.',features:['Static catalog','Accessible controls','Shareable URL'],playUrl:'https://example.com/'},
  {id:'game-009',rank:9,title:'Royal Teen Patti',slug:'royal-teen-patti',image:'assets/images/game-9.svg',category:'teen-patti',bonus:'₹350',rating:'4.1',withdraw:'₹10',featured:false,tags:['teen-patti'],description:'A sample static directory entry for Royal Teen Patti.',features:['Clean detail view','Related games','Theme support'],playUrl:'https://example.com/'}
];
